# Generated by Django 3.0.3 on 2020-02-27 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countmanager', '0002_timeslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='count_end',
        ),
        migrations.RemoveField(
            model_name='session',
            name='count_mid',
        ),
        migrations.RemoveField(
            model_name='session',
            name='count_start',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='name',
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='time_slot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='countmanager.TimeSlot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speaker',
            name='email',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speaker',
            name='first_name',
            field=models.CharField(default=11, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speaker',
            name='last_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speaker',
            name='phone_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='end_time',
            field=models.IntegerField(default=0),
        ),
    ]
