# Generated by Django 3.0.3 on 2020-04-06 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countmanager', '0003_auto_20200227_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginning', models.IntegerField(default=0)),
                ('middle', models.IntegerField(default=0)),
                ('end', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='duration',
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(default=0),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='counts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='countmanager.Counts'),
            preserve_default=False,
        ),
    ]
