# Generated by Django 3.0.3 on 2020-04-06 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countmanager', '0004_auto_20200405_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='counts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countmanager.Counts'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='email',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
