# Generated by Django 3.0.3 on 2020-04-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countmanager', '0005_auto_20200405_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='counts',
        ),
        migrations.AddField(
            model_name='session',
            name='beginning_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='end_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='middle_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
