# Generated by Django 3.0.3 on 2020-04-06 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countmanager', '0006_auto_20200406_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='speaker',
            options={'ordering': ('first_name',)},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ('start_time',)},
        ),
    ]
